name: Build and Push Docker Image

on:
  push:
    branches:
      - moi  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Récupération du code source
        uses: actions/checkout@v3

      - name: 🔐 Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: 🛠️ Construction de l'image Docker
        run: |
          docker build -t docker.io/fatima847/librairie:latest .

      - name: 🚀 Envoi de l'image vers Docker Hub
        run: |
          docker push docker.io/fatima847/librairie:latest

      - name: 🔒 Déconnexion de Docker Hub
        run: |
          docker logout
